name: doc-lint

on: [push, pull_request]

jobs:
    doc_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ChiefGokhlayeh/textidote-action@v5
              with:
                  root_file: docu/report.tex
            - uses: actions/upload-artifact@v4
              with:
                  name: textidote_report
                  path: report.html
