name: pytest

on: [push, pull_request]

jobs:
    pytest:
        runs-on: ubuntu-20.04
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v3
            - name: Cache conda
              uses: actions/cache@v3
              env:
                  # Increase this value to reset cache if environment.yml has not changed
                  CACHE_NUMBER: 0
              with:
                  path: ~/conda_pkgs_dir
                  key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
            - name: Set up Python environment
              uses: conda-incubator/setup-miniconda@v2
              with:
                  miniconda-version: "latest"
                  activate-environment: pluto-sdr-pr
                  environment-file: environment.yml
                  use-only-tar-bz2: true
            - name: Run tests via pytest
              run: conda run -n pluto-sdr-pr pytest --strict-config
